### ISSUE TITLE
All AWS Terraform modules should accept tags to apply on all resources they create

### ISSUE THREAD

**Issue by pturley** [tablexi/terraform_modules#96]
- [x] vpc
- [x] subnets
- [x] eks
- [x] ec2
- [x] alb
- [x] rds
- [x] elasticache
- [ ] s3 - We don't manage s3 in modules outside of the terraform module
- [x] cloudfront

Many others are still to be done

**Comment by phoolish** [comment]
@pturley I think this is done as of #117

**Comment by pturley** [comment]
@phoolish I think you are right
